settings:
  title: 'Status Page'
  url: 'https://status.payvalida.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: prowlarr-update # unique identifier
    name: Prowlarr Update
    group: prowlarr
    # description: 'You write code. They handle the rest.' # default=empty
    url: 'https://prowlarr.servarr.com/v1/ping' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    icon: prowlarr_256.png
  - id: prowlarr-indexers
    name: Prowlarr Indexers
    group: prowlarr
    url: https://indexers.prowlarr.com
    icon: prowlarr_256.png
  - id: prowlarr-website
    name: Prowlarr Website
    group: prowlarr
    url: https://prowlarr.com
    icon: prowlarr_256.png
  - id: lidarr-website
    name: Lidarr Website
    group: lidarr
    url: https://lidarr.audio
    icon: lidarr_256.png
  - id: lidarr-update
    name: Lidarr Update
    group: lidarr
    url: https://lidarr.servarr.com/v1/ping
    icon: lidarr_256.png
  - id: lidarr-api-v04
    name: Lidarr API (v0.4)
    group: lidarr
    url: https://api.lidarr.audio/api/v0.4/
    icon: lidarr_256.png
  - id: lidarr-api-testing
    name: Lidarr Testing API
    group: lidarr
    url: https://api.lidarr.audio/api/testing/
    icon: lidarr_256.png
  - id: lidarr-image-cache
    name: Lidarr Image Cache
    group: lidarr
    url: https://imagecache.lidarr.audio/v1
    icon: lidarr_256.png
  - id: radarr-update
    name: Radarr Update
    group: radarr
    url: https://radarr.servarr.com/v1/ping
    icon: radarr_256.png
  - id: radarr-metadata-v1
    name: Radarr Metadata (v1)
    group: radarr
    url: https://api.radarr.video/v1
    icon: radarr_256.png
  - id: radarr-website
    name: Radarr Website
    group: radarr
    url: https://radarr.video
    icon: radarr_256.png
  - id: readarr-update
    name: Readarr Update
    group: readarr
    url: https://readarr.servarr.com/v1/ping
    icon: readarr_256.png
  - id: readarr-website
    name: Readarr Website
    group: readarr
    url: https://readarr.com
    icon: readarr_256.png
  - id: wiki
    name: Wiki
    group: general
    url: https://wiki.servarr.com
    followRedirect: true
    icon: servarr_dark_256.png
  - id: weblate
    name: Weblate
    group: general
    url: https://translate.servarr.com
    followRedirect: true
    icon: servarr_dark_256.png
  - id: github-bot
    name: GitHub Bot
    group: general
    url: https://githubbot.servarr.com/
    icon: servarr_dark_256.png
  - id: auth-server
    name: OAuth Server
    group: general
    url: https://auth.servarr.com/v1
    icon: servarr_dark_256.png
  - id: prowlarr-requests
    name: Indexer Requests
    group: prowlarr
    expectStatus: 302
    url: https://requests.prowlarr.com/
    icon: prowlarr_256.png
  - id: whisparr-website
    name: Whisparr Website
    group: whisparr
    url: https://whisparr.com
    icon: whisparr_256.png
  - id: whisparr-update
    name: Whisparr Update
    group: whisparr
    url: https://whisparr.servarr.com/v1/ping
    icon: whisparr_256.png
  - id: whisparr-metadata-v1
    name: Whisparr Metadata (v1)
    group: whisparr
    url: https://api.whisparr.com/v1/
    icon: whisparr_256.png
  - id: whisparr-metadata-v2
    name: Whisparr Metadata (v2)
    group: whisparr
    url: https://api.whisparr.com/v2/
    icon: whisparr_256.png

  #####################

  - id: Payválida # unique identifier
    name: Payvalida Page
    url: 'https://payvalida.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    group: General
  
  - id: Documentation Payvalida # unique identifier
    name: Payvalida Documentation
    url: 'https://docs.payvalida.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    group: General

############ Production ###############
  - id: secure-merchant.payvalida.com
    description: 'Billetera Sandbox Payválida.'
    url: 'https://secure-merchant.payvalida.com'
    method: GET
    expectStatus: 200
    linkable: true
    group: Production

  - id: Api Production Payválida # unique identifier
    name: Api Merchants Country Payválida
    url: 'https://api-merchants.payvalida.com/country' # URL to fetch
    method: GET # default=GET
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    group: Production

  - id: www-wallet-com
    name: Wallet Production Payválida
    url: 'https://wallet.payvalida.com'
    method: GET
    linkable: true
    group: Production

  # - id: Api Production Payválida # unique identifier
  #   name: Api Production Payválida
  #   description: 'Api Endpoints Payválida.' # default=empty
  #   url: 'https://api.payvalida.com' # URL to fetch
  #   method: GET # default=GET
  #   followRedirect: true
  #   group: Production

############ Sandbox ###############

  - id: sandbox-wallet-payvalida.com
    name: 'Wallet Sandbox Payválida'
    url: 'https://sandbox-wallet.payvalida.com'
    method: GET
    linkable: true
    group: Sandbox

  - id: sandbox-merchant-payvalida.com
    name: 'Modulo Administrativo Sandbox Payválida'
    url: 'https://sandbox-merchant.payvalida.com'
    method: GET
    linkable: true
    group: Sandbox