settings:
  title: 'Status Page'
  url: 'https://status.payvalida.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  ##################### General ###################

  - id: Payválida # unique identifier
    name: Payvalida Page
    url: 'https://payvalida.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    group: General
  
  - id: Documentation Payvalida # unique identifier
    name: Payvalida Documentation
    url: 'https://docs.payvalida.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    group: General

############ Production ###############
  - id: secure-merchant.payvalida.com
    name: 'Merchants Prod Payválida'
    url: 'https://secure-merchant.payvalida.com'
    method: GET
    expectStatus: 200
    linkable: true
    group: Production
  
  - id: Api Production Payválida # unique identifier
    name: Modulo administrativo Prod Payválida
    url: 'https://secure-administrative.payvalida.com/' # URL to fetch
    method: GET # default=GET
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    group: Production


  - id: Api Production Payválida # unique identifier
    name: Api Merchants Country Payválida
    url: 'https://api-merchants.payvalida.com/country' # URL to fetch
    method: GET # default=GET
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    group: Production

  - id: www-wallet-com
    name: Wallet Production Payválida
    url: 'https://wallet.payvalida.com'
    method: GET
    linkable: true
    group: Production

  - id: Api Production Payválida
    name: Api Production Payválida
    url: 'https://api.payvalida.com'
    method: GET
    followRedirect: true
    group: Production

############ Sandbox ###############

  - id: sandbox-wallet-payvalida.com
    name: 'Wallet Sandbox Payválida'
    url: 'https://sandbox-wallet.payvalida.com'
    method: GET
    linkable: true
    group: Sandbox

  - id: sandbox-merchant-payvalida.com
    name: 'Modulo Administrativo Sandbox Payválida'
    url: 'https://sandbox-merchant.payvalida.com'
    method: GET
    linkable: true
    group: Sandbox
  
  - id: Api Production Payválida # unique identifier
    name: Modulo administrativo Sandbox Payválida
    url: 'https://administrative-test.payvalida.com/' # URL to fetch
    method: GET # default=GET
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    group: Sandbox
