settings:
  title: 'Servarr Status'
  url: 'https://status.servarr.com' # used for Slack messages
  logo: servarr_dark_256.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: prowlarr-update # unique identifier
    name: Prowlarr Update
    group: prowlarr
    # description: 'You write code. They handle the rest.' # default=empty
    url: 'https://prowlarr.servarr.com/v1/ping' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  - id: prowlarr-indexers
    name: Prowlarr Indexers
    group: prowlarr
    url: https://indexers.prowlarr.com
  - id: prowlarr-website
    name: Prowlarr Website
    group: prowlarr
    url: https://prowlarr.com
  - id: lidarr-website
    name: Lidarr Website
    group: lidarr
    url: https://lidarr.audio
  - id: lidarr-update
    name: Lidarr Update
    group: lidarr
    url: https://lidarr.servarr.com/v1/ping
  - id: lidarr-api-v04
    name: Lidarr API (v0.4)
    group: lidarr
    url: https://api.lidarr.audio/api/v0.4/
  - id: lidarr-api-testing
    name: Lidarr Testing API
    group: lidarr
    url: https://api.lidarr.audio/api/testing/
  - id: lidarr-image-cache
    name: Lidarr Image Cache
    group: lidarr
    url: https://imagecache.lidarr.audio/v1
  - id: radarr-update
    name: Radarr Update
    group: radarr
    url: https://radarr.servarr.com/v1/ping
  - id: radarr-metadata-v1
    name: Radarr Metadata (v1)
    group: radarr
    url: https://radarrapi.servarr.com/v1
  - id: radarr-website
    name: Radarr Website
    group: radarr
    url: https://radarr.video
  - id: readarr-update
    name: Readarr Update
    group: readarr
    url: https://readarr.servarr.com/v1/ping
  - id: readarr-website
    name: Readarr Website
    group: readarr
    url: https://readarr.com
  - id: wiki
    name: Wiki
    group: general
    url: https://wiki.servarr.com
    followRedirect: true
  - id: weblate
    name: Weblate
    group: general
    url: https://translate.servarr.com
    followRedirect: true
  - id: github-bot
    name: GitHub Bot
    group: general
    url: https://githubbot.servarr.com/
